### ISSUE TITLE
📆  Iteration plan for V111

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#2002]
This is the work in progress plan for V111

### 🥵 Radiative heat transfer
- [x] feelpp/feelpp#1910 @prudhomm @lberti 
- [x] feelpp/feelpp#1909 @prudhomm @lberti 
- [x] #1892 @prudhomm @lberti 
- [x] feelpp/feelpp#1906 @Zohra-D 
- [ ] feelpp/feelpp#1907 @Zohra-D 
- [ ] feelpp/feelpp#1274 @vincentchabannes 
- [ ] #2043 @lberti 

### 💥 Collision forces
- [x] #1839 @VLCeline @lberti 
- [x] feelpp/feelpp#1836 @VLCeline 
- [x] #1837 @VLCeline @lberti 
- [x] #1807 @VLCeline @lberti 
- [ ] #1429 @prudhomm @lberti @vincentchabannes 
- [x] #2034

## Numerical Methods

- [x] feelpp/feelpp#2026 @lberti 
- [ ] feelpp/feelpp#1848 @prudhomm  
- [x] feelpp/feelpp#1912 @thomas-saigre @alielarif  
- [x] feelpp/feelpp#2004
- [x] #2081 
- [x] #2068 @thomas-saigre 
- [x] #2197 @vincentchabannes 

## DSEL

- [x] #2049 @prudhomm @lberti 
- [ ] #2032 @prudhomm @thomas-saigre 

## Mesh

 - [x] #2019 @prudhomm 
 - [x] #2020 @prudhomm 
 - [ ] #2021 @VLCeline 
 - [x] #2023 @prudhomm 
 - [x] #2095 @prudhomm 

## Study cases

- [x] #2014 @thomas-saigre 

## Engineering

- [ ] feelpp/feelpp#1489 @prudhomm 
- [ ] feelpp/feelpp#2175 @prudhomm 
- [x] feelpp/feelpp#1825 @prudhomm 
- [x] #2008 @prudhomm 
- [x] #2009 @prudhomm 
- [x] #2037 @prudhomm 
- [x] #2076 @prudhomm 
- [x] #2077 @prudhomm 
- [x] #2078 @prudhomm 
- [x] #2082
- [ ] #2091 
- [x] #2086 
- [x] #2131
- [x] #1801 @vincentchabannes 

## Performance

- [x] #2199 @prudhomm 
- [x] #2009 

## Python

- [x] #2028 @prudhomm @thomas-saigre 
- [x] #2013
- [x] #2044 @prudhomm @thomas-saigre 
- [x] #2054 @prudhomm @thomas-saigre 
- [x] #2052 @lberti @prudhomm 
- [x] #2057
- [x] #2058
- [x] #2060
- [x] #2059
- [x] #2061
- [x] #2062
- [x] #2115 

## Install/Update

- [x] #2017
- [ ] feelpp/feelpp.pkg#11
- [ ] #2016
- [ ] feelpp/feelpp#1983 
- [x] #2010
- [x] #2011
- [x] #1893 @prudhomm 
- [x] #2079
- [x] #2135

## Clean Code

- [x] #2012

## Documentation

- [x] feelpp/feelpp#2005
- [ ] feelpp/book.feelpp.org#223
- [ ] feelpp/toolbox#150 @jobinhio
- [ ] feelpp/toolbox#137 @jobinhio
- [ ] feelpp/toolbox#136 @jobinhio
- [ ] package and install feelpp_online_run documentation
