### ISSUE TITLE
add support latest debian and ubuntu distro

### ISSUE THREAD

**Issue by prudhomm** [feelpp/feelpp#2135]
- [x] feelpp/feelpp.pkg#17
- [x] feelpp/feelpp.pkg#14
- [x] feelpp/feelpp.pkg#15
- [x] feelpp/feelpp.pkg#16
- [x] feelpp/docker#53
- [x] #2136

**Comment by prudhomm** [comment]
@vincentchabannes now that debian:12 is out there, I propose that we have the latest ubuntu and debian lts for the docker builds. we drop bullseye and focal.
